services:
  watch-docker:
    image: jianxcao/watch-docker:latest 
    container_name: watch-docker
    ports:
      - "8080:8080"
    volumes:
      - /volume1/docker-data/watch-docker:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
      - USER_NAME=admin
      - USER_PASSWORD=Cidsic-sisjad-ryzmu1
      - PUID=0
      - PGID=0
      - UMASK=0000
    restart: unless-stopped